### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by webdev03** [The-Catalyst-Browser-Project/The-Catalyst-Browser-Project.github.io#1]
I will add this soon with the power of github actions.

**Comment by webdev03** [comment]
Or we can do it with Vercel, what do you think?

**Comment by snowcatridge10** [comment]
Vercel!

**Comment by JaydenDev** [comment]
You cannot host framework websites with GH-Pages

**Comment by JaydenDev** [comment]
Vercel is for WebApps, so is Svelte. You don't need an app to show off an app.

**Comment by JaydenDev** [comment]
Also NPM is standard and is in default Linux repositories, I cannot install it easily. Or at all I mean.

**Comment by JaydenDev** [comment]
I installed it but don't wanna use it :( NPM > pnpm

**Comment by webdev03** [comment]
`npm install -g pnpm`

**Comment by webdev03** [comment]
> Because you're a member of the GitHub organization that you tried to install Vercel's GitHub App on, you first need to wait for an owner of the GitHub organization to approve your installation request.
They just received an email notification from GitHub, in which they are prompted to approve your installation request. Once they've done that, the GitHub organization will automatically show up in the list of Git namespaces that you have access to on Vercel.

**Comment by webdev03** [comment]
@JaydenDev can you let me install Vercel?

**Comment by webdev03** [comment]
@JaydenDev The reason why I made it with Svelte is because 1. it cleans up the code by separation into multiple files, 2. it has incredible browser support, 3. no JS on the client (server side rendering with Vercel), 4. SPA routing is awesome

**Comment by webdev03** [comment]
Catalyst uses plain tailwind, Svelte has support for PostCSS so you can use other plugins such as autoprefixer (which adds the `-webkit-` kind of prefixes)

**Comment by webdev03** [comment]
@JaydenDev can you please install vercel ??

**Comment by webdev03** [comment]
@JaydenDev please?

**Comment by webdev03** [comment]
@JaydenDev Can you enable GH Pages

**Comment by JaydenDev** [comment]
> @JaydenDev Can you enable GH Pages
I don't support this project. There already is a website @ https://jaydendev.github.io/catalyst

**Comment by JaydenDev** [comment]
nvm it has a 404 but still im not doing it.

**Comment by webdev03** [comment]
Why??

**Comment by webdev03** [comment]
That website has a blue rectangle and a word "JaydenDev" on it. What?

**Comment by JaydenDev** [comment]
@webdev03 thats the work in progress 404 page.

**Comment by webdev03** [comment]
Can't we just use this? There are no problems with it.
If you're going to ignore someone's hard work then I'm not going to work with you then.

**Comment by JaydenDev** [comment]
> Can't we just use this? There are no problems with it. If you're going to ignore someone's hard work then I'm not going to work with you then. You ignore people's ideas sometimes.

I am BUSY with like 5 other notifications right now!!!

**Comment by webdev03** [comment]
OK, sorry! I get a lot of notifications too.

**Comment by JaydenDev** [comment]
> OK, sorry! I get a lot of notifications too.

say bye to Catalyst (again) because im archiving the repo!

**Comment by webdev03** [comment]
Archiving the repo isn't the solution. Instead, find a way to make the codebase more maintainable.

**Comment by JaydenDev** [comment]
> Archiving the repo isn't the solution. Instead, find a way to make the codebase more maintainable.
not having a codebase at all is the solution!

**Comment by webdev03** [comment]
That's not a very nice mentality. None of us who work on Catalyst are working for you and getting paid. We're just volunteers.

**Comment by JaydenDev** [comment]
@webdev03 if nobody is going to work on it, archive it. there done.

**Comment by webdev03** [comment]
But you can work on it! @hello-smile6 can work on it!

**Comment by JaydenDev** [comment]
Cleaning up and archiving..

**Comment by JaydenDev** [comment]
> But you can work on it! @hello-smile6 can work on it!

hello-smile6 RUINED freecat oh heck no. Also there is no turning back now! even if i can unarchive it I wont!

**Comment by JaydenDev** [comment]
It should of done it as soon as the gh-pages branch was made. Hope it works now.

**Comment by JaydenDev** [comment]
its hosting now.

**Comment by webdev03** [comment]
Yay

**Comment by webdev03** [comment]
I need to rename the repo

**Comment by webdev03** [comment]
Can you rename it to `The-Catalyst-Browser-Project.github.io` so that it works

**Comment by webdev03** [comment]
because svelte is looking in the wrong place thats why the font is bad

**Comment by JaydenDev** [comment]
want it at the main branch?

**Comment by webdev03** [comment]
NO!

**Comment by webdev03** [comment]
It's written with Svelte so we can't put it on main branch. Just use the gh-pages branch I have it so it auto deploys when we push to main

**Comment by JaydenDev** [comment]
A domain is very much needed. This long URL just won't work! Maybe someday I'll get catalyst.cf

**Comment by webdev03** [comment]
You could buy a domain for your projects, like `jayden.dev` or something

**Comment by JaydenDev** [comment]
> You could buy a domain for your projects, like `jayden.dev` or something
> 
> I'm thinking of getting `devarsh.dev` in the future

buy?
buy?
you know what answer thats going to get you?
NO!, I'm don't have money for a domain!

**Comment by webdev03** [comment]
Oh ok. But can you rename the repo or make me co-owner of the org?

**Comment by JaydenDev** [comment]
being a repository maintainer is hard ya know? :(

**Comment by webdev03** [comment]
am I blocked

**Comment by webdev03** [comment]
Hmm it still doesn't work :/
